export enum HEADING_VARIANTS {
    SMALL_PRIMARY = 'SMALL_PRIMARY',
    SMALL_SECONDARY = 'SMALL_SECONDARY',
    MEDIUM_PRIMARY = 'MEDIUM_PRIMARY',
    MEDIUM_SECONDARY = 'MEDIUM_SECONDARY',
    BIG_PRIMARY = 'BIG_PRIMARY',
    BIG_SECONDARY = 'BIG_SECONDARY'
}
