import '@/style/CSSReset.css'

import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'] })

import { Header } from '@/components'

import { lightTheme } from '@/style/theme.css'
import { container } from './layout.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className={`${rubik.className} ${lightTheme}`}>
                <main className={container}>
                    <Header />
                    {children}
                </main>
            </body>
        </html>
    )
}
